// SPDX-License-Identifier: GPL-3.0-or-later
// Original diagnostic boundaries; no browser/GPU execution or timing claims.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile,writeFile,mkdir,mkdtemp,rm,symlink } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { createServer } from 'node:net';
import { request } from 'node:http';
import { buildGpuVoxelPerformance,repositoryRoot } from './build.mjs';
import { serveGpuVoxelPerformance } from './serve.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
async function port(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const n=s.address().port;await new Promise(r=>s.close(r));return n;}
async function fixture(){await mkdir(resolve(repositoryRoot,'local'),{recursive:true});const root=await mkdtemp(resolve(repositoryRoot,'local/voxel-tools-')),base=resolve(root,'local/build');await mkdir(resolve(base,'dist/LICENSES'),{recursive:true});const files=[];for(const name of ['main.js','index.html','style.css','LICENSE.txt','NOTICES.txt','LICENSES/GPL-3.0-or-later.txt']){const data=Buffer.from('original '+name);await writeFile(resolve(base,'dist',name),data);files.push({name,bytes:data.length,sha256:hash(data)});}const manifest={schema:1,mode:'voxel',files};await writeFile(resolve(base,'manifest.json'),JSON.stringify(manifest));return{root,base,manifest};}
test('voxel server retains immutable code and rejects foreign host/origin, uploads, assets and queries',async()=>{const f=await fixture();let h;try{const n=await port();h=await serveGpuVoxelPerformance('local/build',n,false,f.root);const url=`http://127.0.0.1:${n}`;for(const path of ['/','/main.js','/manifest.json']){const r=await fetch(url+path);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/connect-src 'none'/);assert.equal(r.headers.get('cross-origin-opener-policy'),null);}for(const p of ['/game/asset','/local/secret','/main.js?q=1','/%6dain.js'])assert.equal((await fetch(url+p)).status,404);assert.equal((await fetch(url+'/',{method:'POST',body:'original'})).status,405);assert.equal((await fetch(url+'/',{headers:{Origin:'https://example.invalid'}})).status,403);assert.equal(await new Promise((r,j)=>{const q=request(url,{headers:{Host:'example.invalid'}},res=>{res.resume();res.on('end',()=>r(res.statusCode));});q.on('error',j);q.end();}),403);await writeFile(resolve(f.base,'dist/main.js'),'changed');assert.equal(await(await fetch(url+'/main.js')).text(),'original main.js');}finally{if(h)await new Promise(r=>h.server.close(r));await rm(f.root,{recursive:true,force:true});}});
test('malformed manifests, absent required code, symlinks and wrong output hashes fail closed',async()=>{for(const kind of ['hash','missing','duplicate','path','mode','symlink']){const f=await fixture();try{if(kind==='hash')f.manifest.files[0].sha256='0'.repeat(64);if(kind==='missing')f.manifest.files=f.manifest.files.filter(v=>v.name!=='main.js');if(kind==='duplicate')f.manifest.files.push(f.manifest.files[0]);if(kind==='path')f.manifest.files[0].name='../game/asset';if(kind==='mode')f.manifest.mode='full';if(kind==='symlink'){await rm(resolve(f.base,'dist/main.js'));await symlink('style.css',resolve(f.base,'dist/main.js'));}await writeFile(resolve(f.base,'manifest.json'),JSON.stringify(f.manifest));await assert.rejects(serveGpuVoxelPerformance('local/build',await port(),false,f.root));}finally{await rm(f.root,{recursive:true,force:true});}}});
test('builder refuses literal symlink entrypoints and invalid mode/output before distribution',async()=>{const f=await fixture();try{await assert.rejects(buildGpuVoxelPerformance('local/new','bad',f.root),/mode/);await assert.rejects(buildGpuVoxelPerformance('../escape','voxel',f.root),/ignored local/);await mkdir(resolve(f.root,'tools/gpu-voxel-performance'),{recursive:true});await writeFile(resolve(f.root,'tools/gpu-voxel-performance/actual.mjs'),'console.log("original");');await symlink('actual.mjs',resolve(f.root,'tools/gpu-voxel-performance/main.mjs'));await assert.rejects(buildGpuVoxelPerformance('local/new','voxel',f.root),/Symlink code input refused/);}finally{await rm(f.root,{recursive:true,force:true});}});
async function mounted(){const source=(await readFile(new URL('./main.mjs',import.meta.url),'utf8')).replace(/^import .*;$/gm,'');const nodes=new Map(),events=new Map(),raf=new Map(),reports=[];let next=0;const node=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',hidden:true});return nodes.get(id);};const document={visibilityState:'visible',getElementById:node,querySelector:node,addEventListener:(name,f)=>events.set(name,f)};const window={addEventListener:(name,f)=>events.set(name,f)};class Store{clear(){this.cleared=true;}show(r){reports.push(r);}}Function('document','window','navigator','crossOriginIsolated','devicePixelRatio','ReportStore','requestAnimationFrame','cancelAnimationFrame','GPU_VOXEL_POLICY',source)(document,window,{userAgent:'original'},false,1,Store,f=>{raf.set(++next,f);return next;},id=>raf.delete(id),'original-test-policy');return{nodes,events,document,raf,reports};}
test('hidden, cancel and pagehide abort suspended RAF immediately; pagehide creates no report URL',async()=>{for(const reason of ['hidden','cancel','pagehide']){const f=await mounted();const running=f.nodes.get('refresh').onclick();assert.equal(f.raf.size,1);if(reason==='hidden'){f.document.visibilityState='hidden';f.events.get('visibilitychange')();}else if(reason==='pagehide')f.events.get('pagehide')();else f.nodes.get('cancel').onclick();await running;assert.equal(f.raf.size,0);assert.equal(f.reports.length,reason==='pagehide'?0:1);if(reason!=='pagehide'){assert.equal(f.reports[0].verified,false);assert.match(f.reports[0].error,/hidden|cancelled/);} }});

test('independent bin oracle rejects an omitted entry, duplicate ordering and cropped-box overflow',async()=>{const {checkBinCoverage}=await import('./coverage.mjs');const frame={width:32,height:32},packet={boxes:new Int32Array([15,15,17,17,0,0,0,0,17,17,18,18,0,0,1,0]),offsets:new Uint32Array([0,1,2,3,5]),candidates:new Uint32Array([0,0,0,0,1]),tilesX:2};assert.deepEqual(checkBinCoverage(frame,packet),{boxes:2,tiles:4,joins:5});for(const mutation of ['entry','order','bounds']){const p={...packet,boxes:packet.boxes.slice(),candidates:packet.candidates.slice()};if(mutation==='entry')p.candidates[0]=1;else if(mutation==='order')p.candidates[4]=0;else p.boxes[2]=33;assert.throws(()=>checkBinCoverage(frame,p),/Coverage/);}});

test('cadence option bounds and summaries preserve late completion and unissued work',async()=>{const {cadenceOptions,summarizeCadence}=await import('./cadence.mjs');assert.equal(cadenceOptions(1024,1280,'probe').height,720);for(const args of [[1e9,960,'probe'],[64,1e9,'probe'],[64,960,'bad']])assert.throws(()=>cadenceOptions(...args),/options/);const frames=[{id:1,begin:100,preparedAt:105,submittedAt:105,returnedAt:110},{id:2,begin:1200,preparedAt:1205,submittedAt:1205,returnedAt:1210}],done=[{id:1,metadata:{measured:true},observedAt:150,gpuMs:2},{id:2,metadata:{measured:true},observedAt:2100,gpuMs:3}];const r=summarizeCadence(frames,done,0,2000,[100,1200]);assert.equal(r.submitted,2);assert.equal(r.observedWithinWindow,1);assert.equal(r.observedFps,.5);assert.equal(r.minimumFullSecondObserved,0);assert.equal(r.frameDeadlineMisses,1);assert.equal(r.serviceMs.median,10);});

test('cadence cancellation and failed GPU polling release pending resources before producing a result',async()=>{const code=(await readFile(new URL('./cadence.mjs',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replaceAll('export ','');for(const failure of ['cancel','poll']){let renderer,timing;const raf=new Map();let next=0;class Renderer{constructor(){renderer=this;}load(){}draw(){return{};}dispose(){this.disposed=true;}stats(){return {state:this.disposed?'disposed':'ready'};}}class Timing{constructor(){timing=this;this.pending=[];}begin(){}end(){this.pending.push({});}poll(){if(failure==='poll')throw Error('original fence failure');}dispose(){this.disposed=true;this.pending=[];}}const {runVoxelCadence}=Function('gpuVoxelWorkload','GpuVoxelRenderer','GpuTiming','performance','requestAnimationFrame','cancelAnimationFrame',code+';return {runVoxelCadence};')(()=>({scene:{allocations:{}},frame:{allocations:{}},reference:{instances:[]}}),Renderer,Timing,{now:()=>0},f=>{raf.set(++next,f);return next;},id=>raf.delete(id));const token={},report={environment:{}},p=runVoxelCadence({canvas:{},gl:{getContextAttributes:()=>({})},token,report,check(){},status:{},options:{groups:16,width:960,height:640,warmupMs:2,measureMs:8}});assert.equal(raf.size,1);if(failure==='cancel'){token.reason='cancelled';token.abort();}else{const [id,f]=raf.entries().next().value;raf.delete(id);f(1);}await assert.rejects(p,/cancelled|fence failure/);assert.equal(renderer.disposed,true);assert.equal(timing.disposed,true);assert.equal(timing.pending.length,0);assert.equal(raf.size,0);assert.equal(report.disposed.state,'disposed');}});
