// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 WebRA2 contributors. Original viewport UI; no retail persistence.
import { TerrainController, canPick } from './terrain-controller.ts';
import { terrainText } from './terrain-i18n.ts';
import { formatBytes,type Locale } from './i18n.ts';
import type { Zoom } from './terrain-protocol.ts';
import './terrain.css';
const template=`<a class="skip" href="#terrain-main" data-terrain="skip"></a><div class="layout terrain-layout"><aside class="sidebar"><a class="brand" href="#setup" aria-label="WebRA2"><span class="brand-mark" aria-hidden="true">W</span><span class="brand-word">WEB<span>RA2</span></span></a><nav class="navigation"><a href="#setup" data-terrain="installation"></a><a href="#practice" data-terrain="practice"></a><a class="current" href="#terrain" data-terrain="nav"></a></nav><p class="sidebar-footer" data-terrain="tagline"></p></aside><div class="content"><header class="topbar"><div class="topbar-left"><span data-terrain="stage"></span><b data-terrain="device"></b></div><select id="terrain-locale" aria-label="Language / 語言"><option value="en">English</option><option value="zh-Hant">繁體中文</option></select></header><main id="terrain-main" tabindex="-1"><section class="hero"><div class="eyebrow" data-terrain="kicker"></div><h1 data-terrain="title"></h1><p class="intro" data-terrain="intro"></p></section>
<section class="terrain-setup"><div><label for="terrain-profile" data-terrain="profile"></label><select id="terrain-profile"><option value="ra2" data-terrain="ra2"></option><option value="yr" data-terrain="yr"></option></select></div><div class="terrain-file-buttons"><button id="terrain-folder" data-terrain="folder"></button><button id="terrain-files" data-terrain="files"></button><button id="terrain-clear" class="quiet" data-terrain="replace"></button></div><input id="terrain-folder-input" type="file" multiple webkitdirectory class="file-input" tabindex="-1" aria-hidden="true"><input id="terrain-file-input" type="file" multiple class="file-input" tabindex="-1" aria-hidden="true"><p class="scope-note" data-terrain="fileHelp"></p><p id="terrain-fallback" class="scope-note" data-terrain="fallback" hidden></p><div class="terrain-load"><span id="terrain-selection"></span><button id="terrain-load" class="primary" data-terrain="load"></button><button id="terrain-cancel" data-terrain="cancel"></button></div><p id="terrain-notice" role="status" aria-live="polite"></p><div id="terrain-progress-box" hidden><label for="terrain-progress" id="terrain-phase"></label><progress id="terrain-progress" max="1" value="0"></progress><span id="terrain-bytes"></span></div></section>
<section class="terrain-stage"><div class="terrain-toolbar"><div class="terrain-pan" role="group"><button id="terrain-left">←</button><button id="terrain-up">↑</button><button id="terrain-down">↓</button><button id="terrain-right">→</button></div><label><span data-terrain="zoom"></span> <select id="terrain-zoom"><option value="0.5">50%</option><option value="1" selected>100%</option><option value="2">200%</option><option value="4">400%</option></select></label><button id="terrain-zoom-out">−</button><button id="terrain-zoom-in">+</button><button id="terrain-reset" data-terrain="reset"></button><button id="terrain-pick" data-terrain="pickCenter"></button></div><div id="terrain-canvas-wrap"><canvas id="terrain-canvas" width="960" height="640" tabindex="0" role="img" aria-describedby="terrain-controls terrain-scope"></canvas><p id="terrain-empty" data-terrain="empty"></p><span id="terrain-marker" aria-hidden="true" hidden></span></div><p id="terrain-controls" class="scope-note" data-terrain="controls"></p><p id="terrain-cell" role="status"></p><p id="terrain-scope" class="terrain-scope" data-terrain="scope"></p></section>
<details class="terrain-details"><summary data-terrain="details"></summary><dl id="terrain-metadata"></dl><p><strong data-terrain="policy"></strong><br><span data-terrain="policyValue"></span></p><p data-terrain="diagnostics"></p><pre id="terrain-diagnostics"></pre><p id="terrain-error"></p></details></main></div></div>`;
export function mountTerrain(root:HTMLElement,controller:TerrainController):()=>void{
  root.innerHTML=template;const get=<T extends HTMLElement=HTMLElement>(id:string)=>root.querySelector<T>('#terrain-'+id)!;
  const canvas=get<HTMLCanvasElement>('canvas'),context=canvas.getContext('2d',{alpha:false}),wrap=get('canvas-wrap'),marker=get('marker');
  const click=(id:string,fn:()=>void)=>get(id).addEventListener('click',fn);
  const folder=get<HTMLInputElement>('folder-input'),files=get<HTMLInputElement>('file-input');
  const canFolder='webkitdirectory' in folder;get('folder').hidden=!canFolder;get('fallback').hidden=canFolder;
  click('folder',()=>folder.click());click('files',()=>files.click());for(const input of [folder,files])input.addEventListener('change',()=>{if(input.files?.length)controller.select(input.files);input.value='';});
  click('clear',()=>controller.select([]));click('load',()=>{void controller.load();});click('cancel',()=>controller.cancel());
  get<HTMLSelectElement>('profile').addEventListener('change',()=>controller.setProfile(get<HTMLSelectElement>('profile').value as 'ra2'|'yr'));
  get<HTMLSelectElement>('locale').addEventListener('change',()=>controller.setLocale(get<HTMLSelectElement>('locale').value as Locale));
  get<HTMLSelectElement>('zoom').addEventListener('change',()=>controller.zoom(Number(get<HTMLSelectElement>('zoom').value) as Zoom));
  const zoom=(delta:number)=>{const current=Number(get<HTMLSelectElement>('zoom').value),levels:Zoom[]=[0.5,1,2,4];controller.zoom(levels[Math.max(0,Math.min(3,levels.indexOf(current as Zoom)+delta))]!);};
  click('zoom-in',()=>zoom(1));click('zoom-out',()=>zoom(-1));click('reset',()=>controller.reset());
  click('left',()=>controller.pan(-128,0));click('right',()=>controller.pan(128,0));click('up',()=>controller.pan(0,-128));click('down',()=>controller.pan(0,128));
  const pick=(x:number,y:number)=>{if(!canPick(controller.state,x,y))return;marker.style.left=`${x/canvas.width*100}%`;marker.style.top=`${y/canvas.height*100}%`;void controller.pick(x,y);};
  click('pick',()=>pick(Math.floor(canvas.width/2),Math.floor(canvas.height/2)));
  canvas.addEventListener('keydown',event=>{const pan:Record<string,[number,number]>={ArrowLeft:[-64,0],ArrowRight:[64,0],ArrowUp:[0,-64],ArrowDown:[0,64]};if(Object.hasOwn(pan,event.key)){event.preventDefault();controller.pan(...pan[event.key]!);}else if(['+','=','-','Home','Enter'].includes(event.key)){event.preventDefault();if(event.key==='Home')controller.reset();else if(event.key==='Enter')pick(Math.floor(canvas.width/2),Math.floor(canvas.height/2));else zoom(event.key==='-'?-1:1);}});
  let drag:{id:number;x:number;y:number;distance:number}|null=null;
  canvas.addEventListener('pointerdown',event=>{if(event.button!==0||!controller.state.frame)return;canvas.focus();canvas.setPointerCapture(event.pointerId);drag={id:event.pointerId,x:event.clientX,y:event.clientY,distance:0};});
  canvas.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.id)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;drag.distance+=Math.abs(dx)+Math.abs(dy);drag.x=event.clientX;drag.y=event.clientY;if(drag.distance>4){const rect=canvas.getBoundingClientRect();controller.pan(-dx*canvas.width/rect.width,-dy*canvas.height/rect.height);}});
  canvas.addEventListener('pointerup',event=>{if(!drag||event.pointerId!==drag.id)return;const wasClick=drag.distance<=4;drag=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);if(wasClick){const rect=canvas.getBoundingClientRect();pick(Math.floor((event.clientX-rect.left)/rect.width*canvas.width),Math.floor((event.clientY-rect.top)/rect.height*canvas.height));}});
  canvas.addEventListener('pointercancel',()=>{drag=null;});
  canvas.addEventListener('wheel',event=>{if(!controller.state.frame)return;event.preventDefault();zoom(event.deltaY<0?1:-1);},{passive:false});
  let lastFrame=0,lastLocale='';
  const unsubscribe=controller.subscribe(state=>{
    const t=(key:string)=>terrainText(state.locale,key);
    if(lastLocale!==state.locale){lastLocale=state.locale;document.documentElement.lang=state.locale;for(const element of root.querySelectorAll<HTMLElement>('[data-terrain]'))element.textContent=t(element.dataset.terrain!);root.querySelector('nav')!.setAttribute('aria-label',t('workspace'));root.querySelector('.terrain-pan')!.setAttribute('aria-label',t('pan'));canvas.setAttribute('aria-label',t('canvas'));for(const id of ['left','right','up','down','zoom-in','zoom-out'])get(id).setAttribute('aria-label',t(id==='zoom-in'?'zoomIn':id==='zoom-out'?'zoomOut':id));}
    get<HTMLSelectElement>('locale').value=state.locale;get<HTMLSelectElement>('profile').value=state.profile;
    get('selection').textContent=`${t('selection')}: ${state.files.toLocaleString()} · ${formatBytes(state.bytes,state.locale)}`;get('notice').textContent=t(state.notice);
    get<HTMLButtonElement>('load').disabled=!state.files||state.busy;get<HTMLButtonElement>('cancel').disabled=!state.busy;get<HTMLButtonElement>('clear').disabled=!state.files;
    const p=state.progress;get('progress-box').hidden=!p;if(p){get('phase').textContent=t(p.phase);get<HTMLProgressElement>('progress').max=Math.max(1,p.total);get<HTMLProgressElement>('progress').value=p.completed;get('bytes').textContent=`${formatBytes(p.bytes,state.locale)} · ${t('read')}`;}
    const frame=state.frame;for(const id of ['left','right','up','down','zoom','zoom-in','zoom-out','reset'])get<HTMLButtonElement>(''+id).disabled=!frame;get<HTMLButtonElement>('pick').disabled=!frame||state.busy;get('empty').hidden=!!frame;
    if(frame && frame.frameId!==lastFrame){lastFrame=frame.frameId;canvas.width=frame.camera.width;canvas.height=frame.camera.height;context?.putImageData(new ImageData(new Uint8ClampedArray(frame.rgba),canvas.width,canvas.height),0,0);get<HTMLSelectElement>('zoom').value=String(frame.camera.zoom);marker.hidden=true;}
    else if(!frame && lastFrame){lastFrame=0;context?.clearRect(0,0,canvas.width,canvas.height);}
    marker.hidden=!state.cell;get('cell').textContent=state.cell?`${t('cell')}: ${state.cell.x}, ${state.cell.y}`:t('noCell');
    const metadata=get('metadata');metadata.replaceChildren();if(frame){const s=frame.summary;const entries=[['cells',s.cells.toLocaleString()],['assets',s.assets.toLocaleString()],['decoded',formatBytes(s.decodedBytes,state.locale)],['verified',formatBytes(s.verifiedBytes,state.locale)],['pixels',formatBytes(frame.allocations.totalPixelBytes,state.locale)],['mapHash',s.mapHash],['paletteHash',s.paletteHash]];for(const [key,value]of entries){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(key!);dd.textContent=value!;metadata.append(dt,dd);}get('diagnostics').textContent=s.diagnostics.map(d=>`${d.code}: ${d.count}`).join('\n');}else get('diagnostics').textContent='';
    get('error').textContent=state.error?`${t('errorDetail')}: ${state.error}`:'';
  });
  const resize=()=>{const width=Math.max(1,Math.min(960,Math.floor(wrap.clientWidth)));controller.resize(width,Math.max(1,Math.min(640,Math.round(width*2/3))));};
  const observer=new ResizeObserver(resize);observer.observe(wrap);resize();
  return()=>{unsubscribe();observer.disconnect();context?.clearRect(0,0,canvas.width,canvas.height);canvas.width=1;canvas.height=1;};
}
