// SPDX-License-Identifier: GPL-3.0-or-later
import { beginWorldGesture, updateWorldGesture, finishWorldGesture, type WorldGesture } from './terrain-gestures.ts';
// Copyright 2026 WebRA2 contributors. Original viewport UI; no retail persistence.
import { TerrainController, canPick } from './terrain-controller.ts';
import { campaignText } from './campaign-i18n.ts';
import { terrainText, artworkStatusText } from './terrain-i18n.ts';
import { formatBytes,type Locale } from './i18n.ts';
import type { Zoom } from './terrain-protocol.ts';
import { mountWorld } from './world-view.ts';
import './terrain.css';
const template=`<a class="skip" href="#terrain-main" data-terrain="skip"></a><div class="layout terrain-layout"><aside class="sidebar"><a class="brand" href="#setup" aria-label="WebRA2"><span class="brand-mark" aria-hidden="true">W</span><span class="brand-word">WEB<span>RA2</span></span></a><nav class="navigation"><a href="#setup" data-terrain="installation"></a><a href="#practice" data-terrain="practice"></a><a class="current" href="#terrain" data-terrain="nav"></a></nav><p class="sidebar-footer" data-terrain="tagline"></p></aside><div class="content"><header class="topbar"><div class="topbar-left"><span data-terrain="stage"></span><b data-terrain="device"></b></div><select id="terrain-locale" aria-label="Language / 語言"><option value="en">English</option><option value="zh-Hant">繁體中文</option></select></header><main id="terrain-main" tabindex="-1"><section class="hero"><div class="eyebrow" data-terrain="kicker"></div><h1 data-terrain="title"></h1><p class="intro" data-terrain="intro"></p></section>
<section class="terrain-setup"><div><label for="terrain-profile" data-terrain="profile"></label><select id="terrain-profile"><option value="ra2" data-terrain="ra2"></option><option value="yr" data-terrain="yr"></option></select></div><div class="terrain-file-buttons"><button id="terrain-folder" data-terrain="folder"></button><button id="terrain-files" data-terrain="files"></button><button id="terrain-clear" class="quiet" data-terrain="replace"></button></div><input id="terrain-folder-input" type="file" multiple webkitdirectory class="file-input" tabindex="-1" aria-hidden="true"><input id="terrain-file-input" type="file" multiple class="file-input" tabindex="-1" aria-hidden="true"><p class="scope-note" data-terrain="fileHelp"></p><p id="terrain-fallback" class="scope-note" data-terrain="fallback" hidden></p><div class="terrain-load"><span id="terrain-selection"></span><button id="terrain-load" class="primary" data-terrain="load"></button><button id="terrain-cancel" data-terrain="cancel"></button></div><p id="terrain-notice" role="status" aria-live="polite"></p><div id="terrain-progress-box" hidden><label for="terrain-progress" id="terrain-phase"></label><progress id="terrain-progress" max="1" value="0"></progress><span id="terrain-bytes"></span></div></section>
<section class="terrain-stage"><div class="terrain-toolbar"><div class="terrain-pan" role="group"><button id="terrain-left">←</button><button id="terrain-up">↑</button><button id="terrain-down">↓</button><button id="terrain-right">→</button></div><label><span data-terrain="zoom"></span> <select id="terrain-zoom"><option value="0.5">50%</option><option value="1" selected>100%</option><option value="2">200%</option><option value="4">400%</option></select></label><button id="terrain-zoom-out">−</button><button id="terrain-zoom-in">+</button><button id="terrain-reset" data-terrain="reset"></button><button id="terrain-pick" data-terrain="pickCenter"></button></div><div id="terrain-canvas-wrap"><canvas id="terrain-canvas" width="960" height="640" tabindex="0" role="img" aria-describedby="terrain-controls terrain-scope"></canvas><p id="terrain-empty" data-terrain="empty"></p><span id="terrain-marker" aria-hidden="true" hidden></span><div id="terrain-unit-markers" aria-hidden="true"></div><span id="terrain-box" aria-hidden="true" hidden></span></div><p id="terrain-controls" class="scope-note" data-terrain="controls"></p><p id="terrain-cell" role="status"></p><p id="terrain-artwork" class="terrain-artwork-counts"></p><p id="terrain-scope" class="terrain-scope" data-terrain="scope"></p></section>
<details class="terrain-details"><summary data-terrain="details"></summary><dl id="terrain-metadata"></dl><h3 data-terrain="selectedDetails"></h3><dl id="terrain-object-details"></dl><h3 data-terrain="artworkDetails"></h3><div class="terrain-artwork-table-wrap" tabindex="0"><table class="terrain-artwork-table"><thead><tr><th data-terrain="typeName"></th><th data-terrain="family"></th><th data-terrain="format"></th><th data-terrain="artStatus"></th><th data-terrain="placementCount"></th></tr></thead><tbody id="terrain-artwork-rows"></tbody></table></div><p id="terrain-artwork-omitted"></p><p><strong data-terrain="policy"></strong><br><span data-terrain="policyValue"></span></p><p><strong data-terrain="voxelPolicy"></strong><br><span data-terrain="voxelPolicyValue"></span></p><p data-terrain="diagnostics"></p><pre id="terrain-diagnostics"></pre><p id="terrain-error"></p></details></main></div></div>`;
export function mountTerrain(root:HTMLElement,controller:TerrainController,options:{campaign?:boolean}={}):()=>void{
  root.innerHTML=template;const get=<T extends HTMLElement=HTMLElement>(id:string)=>root.querySelector<T>('#terrain-'+id)!;
  let back:HTMLButtonElement|null=null;
  if(options.campaign){root.querySelector<HTMLElement>('.terrain-setup')!.hidden=true;const link=root.querySelector<HTMLAnchorElement>('a.current')!;link.href='#campaign';back=document.createElement('button');back.className='campaign-mission-back';back.addEventListener('click',()=>{void controller.backCampaigns();});root.querySelector('.hero')!.append(back);}
  const canvas=get<HTMLCanvasElement>('canvas'),context=canvas.getContext('2d',{alpha:false}),wrap=get('canvas-wrap'),marker=get('marker');
  const click=(id:string,fn:()=>void)=>get(id).addEventListener('click',fn);
  const folder=get<HTMLInputElement>('folder-input'),files=get<HTMLInputElement>('file-input');
  const canFolder='webkitdirectory' in folder;get('folder').hidden=!canFolder;get('fallback').hidden=canFolder;
  click('folder',()=>folder.click());click('files',()=>files.click());for(const input of [folder,files])input.addEventListener('change',()=>{if(input.files?.length)controller.select(input.files);input.value='';});
  click('clear',()=>controller.select([]));click('load',()=>{void controller.load();});click('cancel',()=>controller.cancel());
  get<HTMLSelectElement>('profile').addEventListener('change',()=>controller.setProfile(get<HTMLSelectElement>('profile').value as 'ra2'|'yr'));
  get<HTMLSelectElement>('locale').addEventListener('change',()=>controller.setLocale(get<HTMLSelectElement>('locale').value as Locale));
  get<HTMLSelectElement>('zoom').addEventListener('change',()=>controller.zoom(Number(get<HTMLSelectElement>('zoom').value) as Zoom));
  const zoom=(delta:number)=>{const current=Number(get<HTMLSelectElement>('zoom').value),levels:Zoom[]=[0.5,1,2,4];controller.zoom(levels[Math.max(0,Math.min(3,levels.indexOf(current as Zoom)+delta))]!);};
  click('zoom-in',()=>zoom(1));click('zoom-out',()=>zoom(-1));click('reset',()=>controller.reset());
  click('left',()=>controller.pan(-128,0));click('right',()=>controller.pan(128,0));click('up',()=>controller.pan(0,-128));click('down',()=>controller.pan(0,128));
  const pick=(x:number,y:number,additive=false)=>{if(!canPick(controller.state,x,y))return;marker.style.left=`${x/canvas.width*100}%`;marker.style.top=`${y/canvas.height*100}%`;void controller.pick(x,y,additive?'toggle':'replace');};
  click('pick',()=>pick(Math.floor(canvas.width/2),Math.floor(canvas.height/2)));
  canvas.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey)return;const pan:Record<string,[number,number]>={ArrowLeft:[-64,0],ArrowRight:[64,0],ArrowUp:[0,-64],ArrowDown:[0,64]};if(Object.hasOwn(pan,event.key)){event.preventDefault();controller.pan(...pan[event.key]!);}else if(['+','=','-','Home','Enter'].includes(event.key)){event.preventDefault();if(event.key==='Home')controller.reset();else if(event.key==='Enter')pick(Math.floor(canvas.width/2),Math.floor(canvas.height/2));else zoom(event.key==='-'?-1:1);}});
  let drag:WorldGesture|null=null;
  const box=get('box'),unitMarkers=get('unit-markers');
  const point=(event:PointerEvent)=>{const r=canvas.getBoundingClientRect();return r.width>0&&r.height>0?{x:Math.max(0,Math.min(canvas.width-1,(event.clientX-r.left)/r.width*canvas.width)),y:Math.max(0,Math.min(canvas.height-1,(event.clientY-r.top)/r.height*canvas.height))}:null;};
  const token=()=>({frameId:controller.state.frame?.frameId??0,revision:controller.state.frame?.world?.revision??0,epoch:controller.state.interactionEpoch});
  const releaseGesture=()=>{const old=drag;drag=null;box.hidden=true;if(old&&canvas.hasPointerCapture(old.id))canvas.releasePointerCapture(old.id);if(controller.state.interacting)controller.setInteracting(false);};
  canvas.addEventListener('pointerdown',event=>{
    if(!controller.state.frame)return;const p=point(event);if(!p)return;
    if(event.button===2){event.preventDefault();releaseGesture();canvas.focus();void controller.moveAt(Math.floor(p.x),Math.floor(p.y));return;}
    if(![0,1].includes(event.button)||!controller.setInteracting(true))return;
    event.preventDefault();canvas.focus();drag=beginWorldGesture({id:event.pointerId,button:event.button,x:p.x,y:p.y,alt:event.altKey,shift:event.shiftKey},token());
    if(drag){try{canvas.setPointerCapture(event.pointerId);}catch{releaseGesture();}}
  });
  canvas.addEventListener('pointermove',event=>{
    if(!drag)return;const p=point(event),next=p&&updateWorldGesture(drag,event.pointerId,p.x,p.y);if(!next)return;drag=next.gesture;
    if(next.pan)controller.pan(...next.pan);
    if(next.box){const b=next.box;box.hidden=false;box.style.left=`${b.left/canvas.width*100}%`;box.style.top=`${b.top/canvas.height*100}%`;box.style.width=`${(b.right-b.left)/canvas.width*100}%`;box.style.height=`${(b.bottom-b.top)/canvas.height*100}%`;}
  });
  canvas.addEventListener('pointerup',event=>{
    if(!drag||drag.id!==event.pointerId)return;const p=point(event),updated=p&&updateWorldGesture(drag,event.pointerId,p.x,p.y);if(updated)drag=updated.gesture;
    const completed=finishWorldGesture(drag,token());releaseGesture();
    if(completed?.kind==='click')pick(completed.x,completed.y,completed.additive);
    else if(completed?.kind==='box')controller.selectBox(completed.frameId,completed.box,completed.additive);
  });
  canvas.addEventListener('pointercancel',releaseGesture);canvas.addEventListener('lostpointercapture',releaseGesture);canvas.addEventListener('blur',releaseGesture);
  canvas.addEventListener('contextmenu',event=>event.preventDefault());canvas.addEventListener('auxclick',event=>event.preventDefault());
  canvas.addEventListener('wheel',event=>{if(!controller.state.frame||event.ctrlKey||event.metaKey)return;event.preventDefault();releaseGesture();zoom(event.deltaY<0?1:-1);},{passive:false});
  let lastFrame=0,lastLocale='',lastArtworkKey='';
  const unsubscribe=controller.subscribe(state=>{
    const t=(key:string)=>options.campaign&&['title','intro','nav'].includes(key)?campaignText(state.locale,key==='title'?'missionTitle':key==='intro'?'missionIntro':'nav'):terrainText(state.locale,key);if(back){back.textContent=campaignText(state.locale,'back');back.disabled=state.busy;}
    if(drag&&(state.phase!=='ready'||drag.epoch!==state.interactionEpoch||drag.revision!==(state.frame?.world?.revision??0)||drag.mode==='select'&&drag.frameId!==state.frame?.frameId))releaseGesture();
    if(lastLocale!==state.locale){lastLocale=state.locale;document.documentElement.lang=state.locale;for(const element of root.querySelectorAll<HTMLElement>('[data-terrain]'))element.textContent=t(element.dataset.terrain!);root.querySelector('nav')!.setAttribute('aria-label',t('workspace'));root.querySelector('.terrain-pan')!.setAttribute('aria-label',t('pan'));canvas.setAttribute('aria-label',t('canvas'));root.querySelector('.terrain-artwork-table-wrap')!.setAttribute('aria-label',t('artworkDetails'));for(const id of ['left','right','up','down','zoom-in','zoom-out'])get(id).setAttribute('aria-label',t(id==='zoom-in'?'zoomIn':id==='zoom-out'?'zoomOut':id));}
    get<HTMLSelectElement>('locale').value=state.locale;get<HTMLSelectElement>('profile').value=state.profile;
    get('selection').textContent=`${t('selection')}: ${state.files.toLocaleString()} · ${formatBytes(state.bytes,state.locale)}`;get('notice').textContent=t(state.notice);
    get<HTMLButtonElement>('load').disabled=!state.files||state.busy;get<HTMLButtonElement>('cancel').disabled=!state.busy;get<HTMLButtonElement>('clear').disabled=!state.files;
    const p=state.progress;get('progress-box').hidden=!p;if(p){get('phase').textContent=t(p.phase);get<HTMLProgressElement>('progress').max=Math.max(1,p.total);get<HTMLProgressElement>('progress').value=p.completed;get('bytes').textContent=`${formatBytes(p.bytes,state.locale)} · ${t('read')}`;}
    const frame=state.frame;for(const id of ['left','right','up','down','zoom','zoom-in','zoom-out','reset'])get<HTMLButtonElement>(''+id).disabled=!frame;get<HTMLButtonElement>('pick').disabled=!frame||state.busy;get('empty').hidden=!!frame;
    if(frame && frame.frameId!==lastFrame){lastFrame=frame.frameId;canvas.width=frame.camera.width;canvas.height=frame.camera.height;context?.putImageData(new ImageData(new Uint8ClampedArray(frame.rgba),canvas.width,canvas.height),0,0);get<HTMLSelectElement>('zoom').value=String(frame.camera.zoom);marker.hidden=true;}
    else if(!frame && lastFrame){lastFrame=0;context?.clearRect(0,0,canvas.width,canvas.height);}
    unitMarkers.replaceChildren();if(frame){for(const p of frame.controlPoints){if(!state.selectedEntities.includes(p.entityId))continue;const mark=document.createElement('span');mark.className='terrain-unit-marker';mark.style.left=`${p.x/canvas.width*100}%`;mark.style.top=`${p.y/canvas.height*100}%`;unitMarkers.append(mark);}}
    const picked=state.selection;marker.hidden=!picked;get('cell').textContent=picked?.kind==='terrain'?`${t('cell')}: ${picked.cell.x}, ${picked.cell.y}`:picked?.kind==='object'?`${t(picked.object.family)} · ${picked.object.x}, ${picked.object.y}`:t('noCell');
    const selected=get('object-details');selected.replaceChildren();if(picked?.kind==='object'){const o=picked.object;for(const [key,value] of [['objectId',o.id],['format',t(o.format)],['typeName',o.name],['owner',o.owner??'—'],['frame',String(o.frame)],['sourcePath',o.sourcePath],['sourceHash',o.sourceHash],['palettePath',o.palettePath],['paletteHash',o.paletteHash],...(o.voxel?[['partId',o.voxel.partId],['partRole',t(o.voxel.role)],['section',String(o.voxel.section)],['hvaPath',o.voxel.hvaPath],['hvaHash',o.voxel.hvaHash],['hvaSection',String(o.voxel.hvaSection)],['hvaFrame',String(o.voxel.hvaFrame)],['voxelOrdinal',String(o.voxel.voxelOrdinal)]]:[])]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(key!);dd.textContent=value!;selected.append(dt,dd);}}
    get('artwork').textContent=frame?`${t('shown')}: ${frame.summary.artwork.rendered.toLocaleString()} · ${t('unavailable')}: ${frame.summary.artwork.unavailable.toLocaleString()}`:'';
    const artworkKey=frame?frame.summary.contentHash+':'+state.locale:'';if(artworkKey!==lastArtworkKey){lastArtworkKey=artworkKey;const body=get('artwork-rows');body.replaceChildren();if(frame){const a=frame.summary.artwork;for(const row of a.rows){const tr=document.createElement('tr');for(const value of [row.name,t(row.family),t(row.format),artworkStatusText(state.locale,row.status),`${row.rendered} / ${row.placements}`]){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}get('artwork-omitted').textContent=`${t('omittedTypes')}: ${a.omittedTypes} · ${t('truncatedFields')}: ${a.truncatedFields}`;}else get('artwork-omitted').textContent='';}
    const metadata=get('metadata');metadata.replaceChildren();if(frame){const s=frame.summary;const entries=[['cells',s.cells.toLocaleString()],['assets',s.assets.toLocaleString()],['decoded',formatBytes(s.decodedBytes,state.locale)],['verified',formatBytes(s.verifiedBytes,state.locale)],['pixels',formatBytes(frame.allocations.totalPixelBytes,state.locale)],['spriteAssets',s.artwork.assets.toLocaleString()],['spriteDecoded',formatBytes(s.artwork.decodedBytes,state.locale)],['contentHash',s.contentHash],['mapHash',s.mapHash],['paletteHash',s.paletteHash],...(s.artwork.voxel?[['voxelAssets',String(s.artwork.voxel.assets)],['voxelParts',String(s.artwork.voxel.parts)],['voxelGeometry',formatBytes(s.artwork.voxel.geometryBytes,state.locale)]]:[]),...(frame.allocations.voxel?[['voxelPlanes',formatBytes(frame.allocations.voxel.rgbaBytes+frame.allocations.voxel.depthBytes+frame.allocations.voxel.ownerBytes+frame.allocations.voxel.maskBytes,state.locale)],['voxelWork',formatBytes(frame.allocations.voxel.workBytes,state.locale)]]:[])];for(const [key,value]of entries){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(key!);dd.textContent=value!;metadata.append(dt,dd);}get('diagnostics').textContent=[...s.diagnostics.map(d=>`${d.code}: ${d.count}`),...s.artwork.rows.filter(r=>r.reasons.length||r.omittedReasons).map(r=>`${r.name}: ${r.reasons.join(', ')}${r.omittedReasons?' · '+t('omittedReasons')+': '+r.omittedReasons:''}`)].join('\n');}else get('diagnostics').textContent='';
    get('scope').textContent=t('scope')+(frame?.summary.diagnostics.some(d=>d.code==='world-unsupported-required-footprint')?' '+t('worldUnavailable'):'');
    get('error').textContent=state.error?`${t('errorDetail')}: ${state.error}`:'';
  });
  const resize=()=>{const width=Math.max(1,Math.min(960,Math.floor(wrap.clientWidth)));controller.resize(width,Math.max(1,Math.min(640,Math.round(width*2/3))));};
  const observer=new ResizeObserver(resize);observer.observe(wrap);resize();const releaseWorld=mountWorld(root,controller);
  return()=>{releaseGesture();releaseWorld();unsubscribe();observer.disconnect();context?.clearRect(0,0,canvas.width,canvas.height);canvas.width=1;canvas.height=1;};
}
