// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 WebRA2 contributors. Original UI copy.
import type { Locale } from './i18n.ts';
const en = {
  title: 'Field orders', scope: 'Experimental movement on the opening map. Orders use WebRA2 cell movement; combat, mission triggers and victory are not running. Missing artwork does not remove an entity from the world.',
  house: 'Control house', chooseHouse: 'Choose a house', unit: 'Unit selection', chooseUnit: 'Choose a unit or inspect an object', focus: 'Center selected unit', run: 'Run', pause: 'Pause', step: 'Step one tick', stop: 'Stop unit', targetX: 'Target X', targetY: 'Target Y', move: 'Move to cell', picked: 'Move to inspected cell', tick: 'Logical tick', state: 'State SHA-256', model: 'World SHA-256', health: 'Health', unknown: 'Unavailable', owner: 'Owner', position: 'Cell', destination: 'Destination', idle: 'Idle', route: 'Remaining route cells', credit: 'Edge credit', queued: 'Queued orders', movement: 'Movement', supported: 'Available', unsupported: 'Unsupported', reasons: 'Unresolved fields', selected: 'Selected entity', noUnit: 'No entity selected.', trace: 'Recent order and movement events', omitted: 'Additional events omitted', persistence: 'Local world checkpoints', slot: 'Slot', save: 'Save locally', load: 'Restore slot', remove: 'Delete slot', exportSave: 'Export checkpoint', importSave: 'Import checkpoint', exportReplay: 'Export replay', importReplay: 'Validate replay file', verify: 'Verify current replay', storage: 'Three browser-local slots, up to 2 MiB each. Checkpoints and replays contain state and content identities, never game assets. Restore requires this exact world. Original Practice slots stay separate.',
  worldPaused: 'Paused. Issue an order, then step or run.', worldRunning: 'Running at a 15 Hz logical policy.', worldHidden: 'Paused because the page became hidden. Resume explicitly.', worldSaved: 'World checkpoint saved on this browser.', worldLoaded: 'Checkpoint restored. Recording starts from this checkpoint.', worldDeleted: 'Local slot deleted.', worldEmpty: 'This slot is empty.', worldQuota: 'The browser could not allocate storage. Export a checkpoint instead.', worldStorage: 'Local storage is unavailable. Use checkpoint export and import.', worldRejected: 'Operation rejected; the world was not replaced. Check the detail below.', worldVerified: 'Replay verified against its recorded terminal state.', verifiedHash: 'Verified terminal SHA-256', unavailableArt: 'Artwork may be unavailable; orders still use the authoritative cell.', timing: 'Space toggles run/pause, S stops the selected unit, and M moves to the inspected terrain cell when the viewport has focus. At most four ticks are requested at once. Hidden pages pause.', omittedReasons: 'Additional unresolved reasons', source: 'Source row', entity: 'Entity ID', remaining: 'Remaining simulation features'
};
const zh: Record<keyof typeof en, string> = {
  title: '戰場指令', scope: '在首關地圖測試移動。指令使用 WebRA2 格子移動規則，尚未執行戰鬥、任務觸發或勝利判定。缺少影像不會移除世界中的實體。',
  house: '控制陣營', chooseHouse: '選擇陣營', unit: '選取單位', chooseUnit: '選擇單位或查看物件', focus: '置中已選單位', run: '執行', pause: '暫停', step: '前進一刻', stop: '停止單位', targetX: '目標 X', targetY: '目標 Y', move: '移動至格子', picked: '移動至已查看格子', tick: '邏輯刻', state: '狀態 SHA-256', model: '世界 SHA-256', health: '生命值', unknown: '無法取得', owner: '擁有者', position: '格子', destination: '目的地', idle: '閒置', route: '剩餘路徑格數', credit: '邊線進度', queued: '待執行指令', movement: '移動', supported: '可用', unsupported: '未支援', reasons: '未解析欄位', selected: '已選實體', noUnit: '尚未選取實體。', trace: '最近指令與移動事件', omitted: '已省略的其他事件', persistence: '本機世界存檔', slot: '欄位', save: '儲存至本機', load: '還原欄位', remove: '刪除欄位', exportSave: '匯出存檔', importSave: '匯入存檔', exportReplay: '匯出重播', importReplay: '驗證重播檔案', verify: '驗證目前重播', storage: '提供三個瀏覽器本機欄位，每個最多 2 MiB。存檔與重播僅含狀態與內容識別，不包含遊戲資產。還原必須使用完全相同的世界。原有練習存檔另行保留。',
  worldPaused: '已暫停。下達指令後，可逐刻前進或執行。', worldRunning: '以每秒 15 邏輯刻規則執行。', worldHidden: '頁面隱藏，已暫停。請手動恢復執行。', worldSaved: '世界存檔已儲存在此瀏覽器。', worldLoaded: '已還原存檔，從此檢查點開始錄製。', worldDeleted: '已刪除本機欄位。', worldEmpty: '此欄位沒有存檔。', worldQuota: '瀏覽器無法配置儲存空間，請改用匯出存檔。', worldStorage: '本機儲存空間無法使用，請改用存檔匯出與匯入。', worldRejected: '作業遭拒，世界未被取代。請查看下方詳細資訊。', worldVerified: '重播已通過記錄的最終狀態驗證。', verifiedHash: '已驗證最終 SHA-256', unavailableArt: '影像可能尚未支援，指令仍使用權威格子位置。', timing: '視窗取得焦點時，空白鍵可切換執行與暫停，S 可停止已選單位，M 可移動至已查看的地形格子。每次最多要求四刻，頁面隱藏時暫停。', omittedReasons: '其他未解析原因', source: '來源資料列', entity: '實體 ID', remaining: '尚待支援的模擬功能'
};
export function worldText(locale: Locale, key: string): string { return Object.hasOwn(en, key) ? (locale === 'zh-Hant' ? zh : en)[key as keyof typeof en] : locale === 'zh-Hant' ? zh.unknown : en.unknown; }
